MOVE_FILES_TO_PROCESSED_FOLDER: False
ADD_TIMESTAMP_TO_PROCESSED_FILES: True
CARD_IMAGE_FOLDER: "media/cards"
LOG_TO_FILE: False
INPUT_FOLDER: "input"
OUTPUT_FOLDER: "output"
SAVE_CACHE: True
SAVE_CACHE_COPY_AS_CSV: True

# noinspection YAMLIncompatibleTypes
KPIS:
  - display_name: "Set"
    requirements:
      - column: "best_hand"
        operation: "eq"
        value: "Three of a Kind"
  - display_name: "2p"
    requirements:
        - column: "best_hand"
          operation: "eq"
          value: "Two Pair"
  - display_name: "Pair"
    requirements:
        - column: "best_hand"
          operation: "eq"
          value: "One Pair"

