MOVE_FILES_TO_PROCESSED_FOLDER: False
ADD_TIMESTAMP_TO_PROCESSED_FILES: True
CARD_IMAGE_FOLDER: "media/cards"
LOG_TO_FILE: False
INPUT_FOLDER: "input"
OUTPUT_FOLDER: "output"
SAVE_CACHE: True
SAVE_CACHE_COPY_AS_CSV: True

# noinspection YAMLIncompatibleTypes
KPIS:
  - display_name: "WRAP"
    requirements:
      - column: "best_hand_value"
        operation: "ne"
        value: 3
      - column: "draw_straight_outs"
        operation: "gt"
        value: 8
  - display_name: "OESD"
    requirements:
      - column: "best_hand_value"
        operation: "ne"
        value: 3
      - column: "draw_straight_outs"
        operation: "eq"
        value: 8
  - display_name: "GS"
    requirements:
      - column: "best_hand_value"
        operation: "ne"
        value: 3
      - column: "draw_straight_outs"
        operation: "eq"
        value: 4

